from sys import argv
script, filename = argv
print(f"We are goin to remove {filename}")
print("If you dont want hit CTRL + C")
print("If you want to do that press Enter")
input(" Chy dekey ? ")
print("Opening the file...")
target = open(filename, 'w')
print("Esta 3 derr daxl bke")
line1 = ("chony")
line2 = input("")
line3 = input("")
print("Iam goint to write all to a file")
target.write(line1)
target.write("\n")
target.write(line2)
target.write("\n")
target.write(line3)
print("Now we close the file")
target.close()